version: '{build}'
branches:
  only:
  - ffi
skip_tags: true
clone_depth: 10
environment:
  matrix:
  - ruby_version: 193
    ruby_dir: 1.9.1
  - ruby_version: 200
    ruby_dir: 2.0.0
  - ruby_version: 200-x64
    ruby_dir: 2.0.0
  - ruby_version: 21
    ruby_dir: 2.1.0
  - ruby_version: 21-x64
    ruby_dir: 2.1.0
  - ruby_version: 22
    ruby_dir: 2.2.0
  - ruby_version: 22-x64
    ruby_dir: 2.2.0
install:
- ps: >-
    $env:path = "C:\Ruby" + $env:ruby_version + "\bin;" + $env:path

    $tpath = "C:\Ruby" + $env:ruby_version + "\lib\ruby\" + $env:ruby_dir + "\test"

    if ((test-path $tpath) -eq $True){ rm -recurse -force $tpath }

    gem update --system > $null

    if ((gem query -i ffi) -eq $False){ gem install ffi --no-document }

    if ((gem query -i win32-security) -eq $False){ gem install win32-security --no-document }

    if ((gem query -i test-unit -v ">= 3.0") -eq $False){ gem install test-unit --no-document }
cache:
- C:\Ruby193\lib\ruby\gems\1.9.1
- C:\Ruby200\lib\ruby\gems\2.0.0
- C:\Ruby200-x64\lib\ruby\gems\2.0.0
- C:\Ruby21\lib\ruby\gems\2.1.0
- C:\Ruby21-x64\lib\ruby\gems\2.1.0
- C:\Ruby22\lib\ruby\gems\2.2.0
- C:\Ruby22-x64\lib\ruby\gems\2.2.0
build: off
test_script:
- cmd: rake
